# Task 3 – Data Cleaning

## Project Introduction

This project demonstrates professional data cleaning techniques using the Titanic dataset. The objective is to transform a deliberately messy dataset into a clean and analysis-ready dataset using Python, Pandas, and NumPy.

The dataset was systematically inspected for missing values, duplicate records, inconsistent categorical values, incorrect data types, and numerical outliers.

The cleaning process included appropriate missing-value imputation, duplicate removal, categorical standardisation, data type correction, outlier detection using the IQR method, and validation of the final dataset.

The project also compares the dataset quality before and after cleaning to demonstrate the effectiveness of the cleaning process.

### Tools and Technologies

- Python
- Pandas
- NumPy
- Google Colab
- Jupyter Notebook

# Import Libraries

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

# Load the Titanic Dataset

In [2]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(url)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Understand the Dataset

In [3]:
print("Dataset Shape:", df.shape)

Dataset Shape: (891, 12)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
PassengerId,891.0,NaN,NaN,NaN,446.0,257.353842,1.0,223.5,446.0,668.5,891.0
Survived,891.0,NaN,NaN,NaN,0.383838,0.486592,0.0,0.0,0.0,1.0,1.0
Pclass,891.0,NaN,NaN,NaN,2.308642,0.836071,1.0,2.0,3.0,3.0,3.0
Name,891,891,"Dooley, Mr. Patrick",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sex,891,2,male,577,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,714.0,NaN,NaN,NaN,29.699118,14.526497,0.42,20.125,28.0,38.0,80.0
SibSp,891.0,NaN,NaN,NaN,0.523008,1.102743,0.0,0.0,0.0,1.0,8.0
Parch,891.0,NaN,NaN,NaN,0.381594,0.806057,0.0,0.0,0.0,0.0,6.0
Ticket,891,681,347082,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fare,891.0,NaN,NaN,NaN,32.204208,49.693429,0.0,7.9104,14.4542,31.0,512.3292
Cabin,204,147,G6,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Embarked,889,3,S,644,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Initial Dataset Inspection

The Titanic dataset contains passenger information including demographics,
ticket class, fare, and survival status.

Before cleaning, the dataset will be inspected for:
- Missing values
- Duplicate records
- Incorrect data types
- Inconsistent categorical values
- Numerical outliers

# Create a Deliberately Messy Dataset

In [7]:
df_messy = df.copy()

df_messy.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
# Add duplicate rows
df_messy = pd.concat(
    [df_messy, df_messy.iloc[[10, 20, 30]]],
    ignore_index=True
)

print("New shape:", df_messy.shape)

New shape: (894, 12)

In [9]:
# Introduce inconsistent gender values
df_messy.loc[0:4, 'Sex'] = ['M', 'MALE', 'male', 'F', 'FEMALE']

In [10]:
# Introduce extra spaces
df_messy.loc[5:9, 'Sex'] = [
    ' male ',
    ' female ',
    'Male ',
    ' Female',
    'male '
]

In [11]:
# Create missing values
df_messy.loc[40:44, 'Age'] = np.nan

df_messy.loc[50:52, 'Embarked'] = np.nan

df_messy.loc[60:62, 'Fare'] = np.nan

In [12]:
# Create an obvious numeric anomaly
df_messy.loc[70, 'Fare'] = 9999

# Create the Data Quality Report

In [13]:
# Dataset dimensions
print("Rows:", df_messy.shape[0])
print("Columns:", df_messy.shape[1])

Rows: 894
Columns: 12

In [14]:
# Missing values
missing_report = pd.DataFrame({
    'Missing Count': df_messy.isnull().sum(),
    'Missing Percentage': (df_messy.isnull().mean() * 100).round(2)
})

missing_report

             Missing Count  Missing Percentage
PassengerId              0                0.00
Survived                 0                0.00
Pclass                   0                0.00
Name                     0                0.00
Sex                      0                0.00
Age                    181               20.25
SibSp                    0                0.00
Parch                    0                0.00
Ticket                   0                0.00
Fare                     3                0.34
Cabin                  689               77.07
Embarked                 5                0.56

In [15]:
# Duplicate rows
duplicate_count = df_messy.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 3

In [16]:
# Data types
dtype_report = pd.DataFrame({
    'Column': df_messy.columns,
    'Data Type': df_messy.dtypes.astype(str).values
})

dtype_report

         Column Data Type
0   PassengerId     int64
1      Survived     int64
2        Pclass     int64
3          Name    object
4           Sex    object
5           Age   float64
6         SibSp     int64
7         Parch     int64
8        Ticket    object
9          Fare   float64
10        Cabin    object
11     Embarked    object

In [17]:
# Unique values
for column in df_messy.select_dtypes(include='object').columns:
    print(f"\n{column}:")
    print(df_messy[column].unique()[:20])

Name:
['Braund, Mr. Owen Harris'
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'
 'Heikkinen, Miss. Laina' 'Futrelle, Mrs. Jacques Heath (Lily May Peel)'
 'Allen, Mr. William Henry' 'Moran, Mr. James' 'McCarthy, Mr. Timothy J'
 'Palsson, Master. Gosta Leonard'
 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)'
 'Nasser, Mrs. Nicholas (Adele Achem)' 'Sandstrom, Miss. Marguerite Rut'
 'Bonnell, Miss. Elizabeth' 'Saundercock, Mr. William Henry'
 'Andersson, Mr. Anders Johan' 'Vestrom, Miss. Hulda Amanda Adolfina'
 'Hewlett, Mrs. (Mary D Kingcome) ' 'Rice, Master. Eugene'
 'Williams, Mr. Charles Eugene'
 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)'
 'Masselmani, Mrs. Fatima']

Sex:
['M' 'MALE' 'male' 'F' 'FEMALE' ' male ' ' female ' 'Male ' ' Female'
 'male ' 'female']

Ticket:
['A/5 21171' 'PC 17599' 'STON/O2. 3101282' '113803' '373450' '330877'
 '17463' '349909' '347742' '237736' 'PP 9549' '113783' 'A/5. 2151'
 '347082' '350406' '248706' '382652' '244373' '345763' '2649']

Cabin:
[nan 'C85' 'C123' 'E46' 'G6' 'C103' 'D56' 'A6' 'C23 C25 C27' 'B78' 'D33'
 'B30' 'C52' 'B28' 'C83' 'F33' 'F G73' 'E31' 'A5' 'D10 D12']

Embarked:
['S' 'C' 'Q' nan]

In [18]:
# Numerical ranges
numeric_columns = df_messy.select_dtypes(include=np.number).columns

range_report = pd.DataFrame({
    'Minimum': df_messy[numeric_columns].min(),
    'Maximum': df_messy[numeric_columns].max(),
    'Mean': df_messy[numeric_columns].mean(),
    'Median': df_messy[numeric_columns].median()
})

range_report

             Minimum  Maximum        Mean    Median
PassengerId     1.00    891.0  444.573826  444.5000
Survived        0.00      1.0    0.383669    0.0000
Pclass          1.00      3.0    2.307606    3.0000
Age             0.42     80.0   29.726746   28.0000
SibSp           0.00      8.0    0.522371    0.0000
Parch           0.00      6.0    0.381432    0.0000
Fare            0.00   9999.0   43.302094   14.4583

In [19]:
# Save the Before-Cleaning Statistics
before_rows = len(df_messy)
before_nulls = df_messy.isnull().sum().sum()
before_duplicates = df_messy.duplicated().sum()

print("Rows:", before_rows)
print("Total null values:", before_nulls)
print("Duplicate rows:", before_duplicates)

Rows: 894
Total null values: 878
Duplicate rows: 3

In [20]:
# Handle Missing Values
df_messy.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            181
SibSp            0
Parch            0
Ticket           0
Fare             3
Cabin          689
Embarked         5
dtype: int64

# Age — Median Imputation

### Missing Age

Age is a numerical variable. Median imputation is selected because age
may contain extreme values, and the median is less affected by outliers
than the mean.

Therefore, missing Age values will be replaced with the median Age.

In [21]:
age_median = df_messy['Age'].median()

df_messy['Age'] = df_messy['Age'].fillna(age_median)

print("Missing Age values:", df_messy['Age'].isnull().sum())

Missing Age values: 0

# Handle Missing Embarked

### Missing Embarked

Embarked is a categorical variable. Since only a small number of values
are missing, mode imputation is appropriate.

The most frequently occurring embarkation location will be used.

In [22]:
embarked_mode = df_messy['Embarked'].mode()[0]

df_messy['Embarked'] = df_messy['Embarked'].fillna(embarked_mode)

print("Missing Embarked values:", df_messy['Embarked'].isnull().sum())

Missing Embarked values: 0

# Handle Missing Fare

### Missing Fare

Fare is a numerical variable. Median imputation is used because ticket
fares contain extreme values, making the median more robust than the mean.

In [23]:
fare_median = df_messy['Fare'].median()

df_messy['Fare'] = df_messy['Fare'].fillna(fare_median)

print("Missing Fare values:", df_messy['Fare'].isnull().sum())

Missing Fare values: 0

# Handle Cabin

### Missing Cabin

The Cabin column contains a large number of missing values. Removing
all rows with missing Cabin information would result in substantial
data loss.

Therefore, a new binary feature `CabinKnown` will be created to indicate
whether cabin information is available. The original Cabin column will
then be removed because it is not required for this cleaning exercise.

In [24]:
df_messy['CabinKnown'] = df_messy['Cabin'].notnull().astype(int)

df_messy.drop(columns=['Cabin'], inplace=True)

df_messy.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,CabinKnown
0,1,0,3,"Braund, Mr. Owen Harris",M,22.0,1,0,A/5 21171,7.2500,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",MALE,38.0,1,0,PC 17599,71.2833,C,1
2,3,1,3,"Heikkinen, Miss. Laina",male,26.0,0,0,STON/O2. 3101282,7.9250,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",F,35.0,1,0,113803,53.1000,S,1
4,5,0,3,"Allen, Mr. William Henry",FEMALE,35.0,0,0,373450,8.0500,S,0

# Remove Duplicate Rows

In [25]:
print("Duplicate rows before removal:", df_messy.duplicated().sum())

Duplicate rows before removal: 3

In [26]:
duplicates_removed = df_messy.duplicated().sum()

df_messy = df_messy.drop_duplicates().reset_index(drop=True)

print("Duplicates removed:", duplicates_removed)
print("Dataset shape after removal:", df_messy.shape)

Duplicates removed: 3
Dataset shape after removal: (891, 12)

### Duplicate Removal

Exact duplicate rows were removed because they represent repeated records
and could cause bias during analysis.

Only exact duplicate records were removed. Similar-looking but potentially
valid passenger records were retained.

# Standardise Gender

In [27]:
df_messy['Sex'].value_counts(dropna=False)

Sex
male        573
female      309
M             1
MALE          1
F             1
 male         1
FEMALE        1
 female       1
Male          1
 Female       1
male          1
Name: count, dtype: int64

In [28]:
df_messy['Sex'] = (
    df_messy['Sex']
    .astype(str)
    .str.strip()
    .str.lower()
    .replace({
        'm': 'male',
        'male': 'male',
        'f': 'female',
        'female': 'female'
    })
)

df_messy['Sex'].value_counts()

Sex
male      578
female    313
Name: count, dtype: int64

In [29]:
df_messy['Sex'] = df_messy['Sex'].str.title()

df_messy['Sex'].value_counts()

Sex
Male      578
Female    313
Name: count, dtype: int64

### Gender Standardisation

Gender values contained inconsistent capitalization, abbreviations,
and whitespace.

Values such as `M`, `male`, and `MALE` were standardised to `Male`,
while `F`, `female`, and `FEMALE` were standardised to `Female`.

# Standardise Embarked

In [30]:
df_messy['Embarked'] = (
    df_messy['Embarked']
    .astype(str)
    .str.strip()
    .str.upper()
)

In [31]:
df_messy['Embarked'].value_counts()

Embarked
S    647
C    167
Q     77
Name: count, dtype: int64

# Correct Data Types

In [32]:
df_messy.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
CabinKnown       int64
dtype: object

In [33]:
df_messy['PassengerId'] = df_messy['PassengerId'].astype(str)

df_messy['Survived'] = df_messy['Survived'].astype(int)

df_messy['Pclass'] = df_messy['Pclass'].astype(int)

df_messy['Age'] = pd.to_numeric(df_messy['Age'], errors='coerce')

df_messy['Fare'] = pd.to_numeric(df_messy['Fare'], errors='coerce')

df_messy['SibSp'] = df_messy['SibSp'].astype(int)

df_messy['Parch'] = df_messy['Parch'].astype(int)

df_messy['CabinKnown'] = df_messy['CabinKnown'].astype(int)

In [34]:
df_messy.dtypes

PassengerId     object
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
CabinKnown       int64
dtype: object

# Detect Outliers Using IQR

In [35]:
numeric_columns = ['Age', 'Fare', 'SibSp', 'Parch']

outlier_report = []

for column in numeric_columns:
    Q1 = df_messy[column].quantile(0.25)
    Q3 = df_messy[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df_messy[
        (df_messy[column] < lower_bound) |
        (df_messy[column] > upper_bound)
    ]

    outlier_report.append({
        'Column': column,
        'Q1': Q1,
        'Q3': Q3,
        'IQR': IQR,
        'Lower Bound': lower_bound,
        'Upper Bound': upper_bound,
        'Outlier Count': len(outliers)
    })

outlier_report = pd.DataFrame(outlier_report)

outlier_report

  Column      Q1    Q3     IQR  Lower Bound  Upper Bound  Outlier Count
0    Age  22.000  35.0  13.000       2.5000      54.5000             66
1   Fare   7.925  31.0  23.075     -26.6875      65.6125            115
2  SibSp   0.000   1.0   1.000      -1.5000       2.5000             46
3  Parch   0.000   0.0   0.000       0.0000       0.0000            213

# Investigate the Fare Outlier

In [36]:
df_messy[df_messy['Fare'] > 1000]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,CabinKnown
70,71,0,2,"Jenkin, Mr. Stephen Curnow",Male,32.0,0,0,C.A. 33111,9999.0,S,0

### Fare Outlier Treatment

The Fare column contains an extreme value of 9999, which is inconsistent
with the normal fare distribution and was identified as an artificial
data-entry anomaly.

Because this value is considered invalid rather than a legitimate extreme
observation, it will be replaced with the median Fare value.

In [37]:
fare_median = df_messy['Fare'].median()

df_messy.loc[df_messy['Fare'] > 1000, 'Fare'] = fare_median

In [38]:
df_messy['Fare'].describe()

count    891.000000
mean      32.065744
std       49.639526
min        0.000000
25%        7.925000
50%       14.458300
75%       30.847900
max      512.329200
Name: Fare, dtype: float64

# Final Missing Value Check

In [39]:
df_messy.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
CabinKnown     0
dtype: int64

# Final Duplicate Check

In [40]:
print("Duplicate rows:", df_messy.duplicated().sum())

Duplicate rows: 0

# Final Data Type Check

In [41]:
df_messy.dtypes

PassengerId     object
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
CabinKnown       int64
dtype: object

# Create After-Cleaning Statistics

In [42]:
after_rows = len(df_messy)
after_nulls = df_messy.isnull().sum().sum()
after_duplicates = df_messy.duplicated().sum()

# Before vs After Summary

In [43]:
comparison = pd.DataFrame({
    'Metric': [
        'Row Count',
        'Total Null Values',
        'Duplicate Rows'
    ],
    'Before Cleaning': [
        before_rows,
        before_nulls,
        before_duplicates
    ],
    'After Cleaning': [
        after_rows,
        after_nulls,
        after_duplicates
    ]
})

comparison

              Metric  Before Cleaning  After Cleaning
0          Row Count              894             891
1  Total Null Values              878               0
2     Duplicate Rows                3               0

# Final Dataset Inspection

In [44]:
df_messy.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,CabinKnown
0,1,0,3,"Braund, Mr. Owen Harris",Male,22.0,1,0,A/5 21171,7.2500,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Male,38.0,1,0,PC 17599,71.2833,C,1
2,3,1,3,"Heikkinen, Miss. Laina",Male,26.0,0,0,STON/O2. 3101282,7.9250,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Female,35.0,1,0,113803,53.1000,S,1
4,5,0,3,"Allen, Mr. William Henry",Female,35.0,0,0,373450,8.0500,S,0
5,6,0,3,"Moran, Mr. James",Male,28.0,0,0,330877,8.4583,Q,0
6,7,0,1,"McCarthy, Mr. Timothy J",Female,54.0,0,0,17463,51.8625,S,1
7,8,0,3,"Palsson, Master. Gosta Leonard",Male,2.0,3,1,349909,21.0750,S,0
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",Female,27.0,0,2,347742,11.1333,S,0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",Male,14.0,1,0,237736,30.0708,C,0

In [45]:
df_messy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    object
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
 11  CabinKnown   891 non-null    int64
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [46]:
df_messy.describe()

,Survived,Pclass,Age,SibSp,Parch,Fare,CabinKnown
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,29.387396,0.523008,0.381594,32.065744,0.228956
std,0.486592,0.836071,12.980188,1.102743,0.806057,49.639526,0.420397
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,22.000000,0.000000,0.000000,7.925000,0.000000
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.458300,0.000000
75%,1.000000,3.000000,35.000000,1.000000,0.000000,30.847900,0.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,1.000000

# Final Data Quality Validation

In [47]:
print("========== FINAL DATA QUALITY CHECK ==========")

print("Rows:", df_messy.shape[0])
print("Columns:", df_messy.shape[1])
print("Total missing values:", df_messy.isnull().sum().sum())
print("Duplicate rows:", df_messy.duplicated().sum())

print("\nData Types:")
print(df_messy.dtypes)

print("\nGender Values:")
print(df_messy['Sex'].unique())

print("\nEmbarked Values:")
print(df_messy['Embarked'].unique())

========== FINAL DATA QUALITY CHECK ==========
Rows: 891
Columns: 12
Total missing values: 0
Duplicate rows: 0

Data Types:
PassengerId     object
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
CabinKnown       int64
dtype: object

Gender Values:
['Male' 'Female']

Embarked Values:
['S' 'C' 'Q']

# Save Cleaned Dataset

In [48]:
output_file = "cleaned_titanic.csv"

df_messy.to_csv(output_file, index=False)

print(f"Cleaned dataset saved as: {output_file}")

Cleaned dataset saved as: cleaned_titanic.csv

# Download the CSV from Colab

In [49]:
from google.colab import files

files.download("cleaned_titanic.csv")

# Conclusion

This project demonstrated a systematic approach to cleaning a deliberately messy Titanic dataset using Python, Pandas, and NumPy.

The dataset was examined for missing values, duplicate records, inconsistent categorical formatting, incorrect data types, and numerical outliers. Appropriate cleaning strategies were selected based on the characteristics of each column rather than applying the same method to all data.

Missing numerical values were handled using median imputation, categorical missing values were handled using mode imputation, duplicate records were removed, inconsistent gender values were standardised, and appropriate data types were assigned to the columns.

Outlier analysis using the IQR method helped identify unusual numerical values. The artificially introduced Fare value of 9999 was identified as an invalid data-entry anomaly and replaced with the median Fare value.

Finally, the cleaned dataset was validated using missing-value checks, duplicate checks, data-type verification, and a before-versus-after quality comparison. The resulting dataset is cleaner, more consistent, and ready for further analysis.